ServerName localhost

# Permite .htaccess (necesario para URLs amigables, frameworks...)
<Directory /var/www/html>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
