ServerName localhost

# Permite .htaccess (necesario para URLs amigables, frameworks...)
<Directory /var/www/html>
    Options Indexes FollowSymLinks
    # Mostra a listaxe mesmo se existe index.php ou index.html.
    DirectoryIndex disabled
    AllowOverride All
    Require all granted
</Directory>
